config/routes.rb
Rails.application.routes.draw do
  
  

  devise_for :admins
  root 'pages#index'
  resources :posts, except: [:index, :new, :destroy, :edit] do
    resources :comments
  end 

  get '/media', to: 'media#index'

  get '/about', to: 'pages#about'
  
  get '/blog', to:  'posts#index'
  get '/newpost', to: 'posts#new'
  
  get '/posts/:id/edit', to: 'posts#edit', as: 'edit'
    
  delete '/posts/:id', to: 'posts#destroy', as: 'destroy', method: :delete
  resources :pictures
  resources :galleries, except: [:delete]
  delete '/galleries/:id', to: 'galleries#destroy', as: 'delete', method: :delete
  

match 'contacts',     to: 'contacts#new',             via: 'get'
resources "contacts", only: [:new, :create]
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "HYC messages",
      :to => "dhamtsik@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	has_many :pictures, dependent: :destroy

	
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	has_attached_file :image, :styles => {:large => "600x600>", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	belongs_to :gallery
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
	def index
		@comments = Comment.all("created_at DESC")
	end
  def new
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.new
  end

  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.build(comment_params)
  	if @comment.save
  		redirect_to blog_path, notice: "Your comment has been posted!"

  	else 
  	 render :new
  	end 
  end

  def show
  	@comment = Comment.find(params[:id])
  end 

  def destroy
    
    @post = Post.find(params[:id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to blog_path, alert: "your comment was deleted"

  	
  end

  def edit
  end

  private
  def comment_params
  	params.require(:comment).permit(:name, :body)
  end 
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  	@contact = Contact.new
  end

  def create
  	@contact = Contact.new(contact_param)
  	@contact.request = request
  	if @contact.deliver
  		flash.now[:alert] = 'Thank you'

  	else 
  		flash.now[:error] ='Cannot send message.'
  		render :new 
  	end 
  end

  private 
  def contact_param
  	params[:contact]
  end 
  
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

	def index
		@galleries = Gallery.all
	end

	def new
		@gallery = Gallery.new(params[:id])
	end

	def show
		@picture = Picture.new
		@gallery = Gallery.find(params[:id])
	end

	def edit
	end

	def create
		@gallery = Gallery.new(event: params[:gallery][:event])
		if @gallery.save
			redirect_to @gallery
		else 
			render :new
		end 
	end

	def update
	end

	def destroy
		@gallery = Gallery.find(params[:id])
		@gallery.destroy
		redirect_to galleries_path

	end

end

app/controllers/media_controller.rb
class MediaController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def gallery
    @picture = Picture.last
  end

  def blog
   
  end

  def contact
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	def index
		@picture = Picture.all
	end 
	
	def new
	  	@picture = Picture.new
	end

  def create
  	@picture = Picture.new(picture_params)
  	if @picture.save
  			redirect_to @picture.gallery
  	else
     		render :new
   	end
  end
  
  def show
  end 
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to @picture.gallery

  end 


  def gallery
		@picture = Picture.last
	end

private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

def picture_params
  params.require(:picture).permit(:image, :gallery_id)
end
 

end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_admin!, except: [:index, :show]
	def index
		@posts = Post.all.order('created_at DESC')
		# @post = Post.new
		@comment = Comment.new
	end

	def new
		@post = Post.new
	end 

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to blog_path, notice: "Your post has been created!"

		else 
			render :new
		end 
	end

	def show
		set_param
		
	end 


	def edit
		@post = Post.find(params[:id])
		redirect_to newpost_path

	end 

	def update
	end 

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to blog_path, alert: "your post was deleted"

	end 

	private

	def post_params
		params.require(:post).permit(:post, :title)
	end 

	def set_param
		@post = Post.find(params[:id])
	end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comment/_new.html.erb
<%= form_for [post, comment] do |f| %>
		<div class="commentname">
			
			<p><%= f.text_field :name, placeholder: :name %></p>
		
			
			<p><%= f.text_area :body, placeholder: :comment  %></p>
		</div>
		<p>
			<%= f.submit "Comment"%>
		</p>
	<% end %>

app/views/comment/edit.html.erb
<h1>Comment#edit</h1>
<p>Find me in app/views/comment/edit.html.erb</p>

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<br>
<body class="contactpage">
	<div class="contactbox">
  	<div class="contactheader">
  		For booking inquiries, please send an email to phirojmusic@gmail.com
  		<br><br><a class="logos" href="mailto:phirojmusic@gmail.com" target="_blank">
		  	<img class="mailto" src="assets/mail.png">
		  </a>
    </div>

    

	</div>

	
</body>

app/views/galleries/_form.html.erb
<%= form_for (@gallery) do |f| %>
	<p>
		<%= f.label :event %>
		<%= f.text_field :event %>
	</p>
	
	<p>
		<%= f.submit "submit"%>
	</p>
<% end %>

app/views/galleries/index.html.erb
<body class="gallerypage">
	<br>
	<div class="gallerybox">
	<div class="galary_header">Photo Albums</div> 
	
	<% @galleries.each do |gallery| %>
		<%= link_to gallery.event, gallery, class: "gallerytitle" %></br>
		<% if admin_signed_in? %>
			<%= link_to 'Delete', delete_path(gallery), class: "eventdelete",method: :delete %></br>

		<% end %>
	<% end %>
	</div>
</body>

app/views/galleries/new.html.erb
<br>
<h1 style="margin-top: 150px"> Title of Gallery </h1>
	<%= render 'form' %>

	<%# render 'pictures/form' %>

app/views/galleries/show.html.erb
<body class="gallerypage"><br>
<div class="container" 
		 style="width: 100%; background-color: #000 		
		 background: url('bd.png') no-repeat center center fixed; 
  	 -webkit-background-size: cover;
  	 -moz-background-size: cover;
  	 -o-background-size: cover;
  	 background-size: cover;">
    <div class="row">
    	<div class="eventtitle"><%= @gallery.event %>
    	</div>
    	<% if admin_signed_in? %>
			<%= render 'pictures/form' %>
		<% end %>
			<br>
		<% @gallery.pictures.each do |pic| %>
		<div class="col-lg-3 col-sm-3 col-xs-6"><a href="#">
			<%= image_tag pic.image.url(:medium), class: "thumbnail img-responsive" %></a>
		</div>
				
			<% if admin_signed_in? %>
	 			<div class="del">
				<%= link_to 'Delete', picture_path(pic.id), class: "eventdelete", method: :delete %>
				</div>
			<% end %>
		<%end %>
  	</div>
</div>
	<div id="myModal" style="margin-top: 100px" class="modal fade" tabindex="-1" role="dialog">
  	<div class="modal-dialog">
  	<div class="modal-content">
	<div class="modal-body">	
	</div>
	<div class="modal-footer">
		<button class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
   </div>
  </div>
</div>
<script>
$('.thumbnail').click(function(){
  	$('.modal-body').empty();
  	var title = $(this).parent('a').attr("title");
  	$('.modal-title').html(title);
  	$($(this).parents('div').html()).appendTo('.modal-body');
  	$('#myModal').modal({show:true});
});
</script>

app/views/media/index.html.erb
<br>
<div id="music">
    <h1 class='navname'>Shyangden Phiroj</h1>
        <div id='about'>
<!--             <h1 class='about_title'>About</h1> -->
            <div id='connect'>
                <p id='bio'>Based in Queens, New York, Shyangden Phiroj is a world-renown guitarist. A founding member of one of Nepal's most famous rock bands, 1974 AD, his playing style implements various genres, including Nepali folk, ragas, rock, funk, blues and jazz. </p>
            </div>
        </div>

        <h1 class='music_title'>Music</h1>
            <ul class="list-unstyled">
                <li><iframe width="500px" height="100px" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/214137704&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe></a></li>
                <br>
                <li><iframe width="500px" height="100px" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/198769237&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe></li>
                <br>
                <li><iframe width="500px" height="100px" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/200450413&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe></li>
            </ul>


        <div id='contact'>
            <h1 class='contact_title'>Social</h1>
<!--                 <div id='connect'>
                    <p id='email'>For booking inquiries, please connect via the links below: </p>
                </div> -->
                    <div class='social'>

                      <span>  <a href="https://soundcloud.com/shyangden-phiroj" target="_blank"><img class='slinks' src="assets/sc2.png"></a>
                        <a href="https://www.facebook.com/pages/Phiroj-Shyangden/281762140542" target="_blank"><img class='slinks' src="assets/fb2.png"></a>
                        <a href="https://www.linkedin.com/pub/phiroj-shyangden/7a/948/186" target="_blank"><img class='slinks' src="assets/li2.png"></a>
                        <a href="https://www.youtube.com/channel/UCrHstpw9XwH9uydjNpl8d9g" target="_blank"><img class='slinks' src="assets/yt2.png"></a>
                        <a href="mailto:phirojmusic@gmail.com" target="_blank">
                        <img class="slinks" src="assets/mail.png"></a></span>
                    </div>
                </div>
        </div>

app/views/pictures/_form.html.erb
<%= form_for @picture, :html => { :multipart => true } do |form| %>
  
  	<div>
  		<%= form.file_field :image %>
	</div>
	<div>
  		<%= form.hidden_field :gallery_id, value: params[:id]  %>
	</div>

<div>	
  <%= form.submit %>
</div>
<% end %>

app/views/pictures/new.html.erb
<%= form_for @picture, :html => { :multipart => true } do |form| %>
  <%= form.file_field :image %>

  <%= form.submit %>
<% end %>

app/views/posts/_form.html.erb
<% if admin_signed_in? %>

	<%= form_for @post do |f| %>
		<p>
			<%= f.label :title %>
			<%= f.text_field :title %>
		</p>
		<p>
			<%= f.label :post %>
			<%= f.text_area :post %>
		</p>
		<p>
			<%= f.submit "Post"%>
		</p>
	<% end %>
<% end %>

app/views/posts/index.html.erb
<body style="background-color: #000">
<br>
    <div class="postbody">
        <div class="container" style="width: 100%;">


        <div class="row">
            <div class="box">
                
                    <% @posts.each do |post| %>
                    <div class="col-lg-12">
                       <div class="posttitle"> <%= post.title %>
                        <% if current_admin %>
                        
                          <%= link_to 'Delete', destroy_path(post), method: :delete, data:{ deletable: true}, class: "delete-btttn" %>

                         <%= link_to 'Edit', edit_path(post), class: "edit-btttn" %>
                   <% end%>
                  </div> 
              </div> <br>     
                        
                <p class="message"><%= post.post %></p>

<!-- 				<div class="commentbutton">	
                    <a href="#" class="test" data-toggle="modal" data-target="#myModal">Comment</a>
                </div> -->
<!-- Modal -->
            <div id="myModal" class="modal fade" role="dialog">
             <div class="modal-dialog modal-sm">
                <div class="modal-content">
                        <div class="modal-header">
                             <button type="button" class="close" data-dismiss="modal">&times;</button>
                              <h4 class="modal-title">Comment</h4>
                        </div>

                    <div class="modal-body">
                         <%= render partial: 'comment/new', locals: { post: post, comment: @comment } %>  
                    </div>

                </div>
             </div>
            </div> 
                    <div class="comments">
                        <%post.comments.count %>            
                        <% post.comments.each do |comment| %> <br>
                        <%= comment.name %>  
                         : <%= comment.body %>
                        <% end %> 
                     </div>
                    <div class="whitespace"></div>
            <% end %>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
    <!-- /.container -->

app/views/posts/new.html.erb
<br>

<div class="newpostform">
	<h1>Post title and content</h1>
	<%= render 'posts/form'  %>
</div>