config/routes.rb
Rails.application.routes.draw do
  
  

  devise_for :admins
  root 'pages#index'
  resources :posts, except: [:index, :new, :destroy, :edit] do
    resources :comments
  end 

  get '/media', to: 'media#index'

  get '/about', to: 'pages#about'
  
  get '/blog', to:  'posts#index'
  get '/newpost', to: 'posts#new'
  
  get '/posts/:id/edit', to: 'posts#edit', as: 'edit'
    
  delete '/posts/:id', to: 'posts#destroy', as: 'destroy', method: :delete
  resources :pictures
  resources :galleries, except: [:delete]
  delete '/galleries/:id', to: 'galleries#destroy', as: 'delete', method: :delete
  

match 'contacts',     to: 'contacts#new',             via: 'get'
resources "contacts", only: [:new, :create]
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "HYC messages",
      :to => "dhamtsik@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	has_many :pictures, dependent: :destroy

	
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	has_attached_file :image, :styles => {:large => "600x600>", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	belongs_to :gallery
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
	def index
		@comments = Comment.all("created_at DESC")
	end
  def new
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.new
  end

  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.build(comment_params)
  	if @comment.save
  		redirect_to blog_path, notice: "Your comment has been posted!"

  	else 
  	 render :new
  	end 
  end

  def show
  	@comment = Comment.find(params[:id])
  end 

  def destroy
    
    @post = Post.find(params[:id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to blog_path, alert: "your comment was deleted"

  	
  end

  def edit
  end

  private
  def comment_params
  	params.require(:comment).permit(:name, :body)
  end 
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  	@contact = Contact.new
  end

  def create
  	@contact = Contact.new(contact_param)
  	@contact.request = request
  	if @contact.deliver
  		flash.now[:alert] = 'Thank you'

  	else 
  		flash.now[:error] ='Cannot send message.'
  		render :new 
  	end 
  end

  private 
  def contact_param
  	params[:contact]
  end 
  
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def gallery
    @picture = Picture.last
  end

  def blog
   
  end

  def contact
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	def index
		@picture = Picture.all
	end 
	
	def new
	  	@picture = Picture.new
	end

  def create
  	@picture = Picture.new(picture_params)
  	if @picture.save
  			redirect_to @picture.gallery
  	else
     		render :new
   	end
  end
  
  def show
  end 
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to @picture.gallery

  end 


  def gallery
		@picture = Picture.last
	end

private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

def picture_params
  params.require(:picture).permit(:image, :gallery_id)
end
 

end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_admin!, except: [:index, :show]
	def index
		@posts = Post.all.order('created_at DESC')
		# @post = Post.new
		@comment = Comment.new
	end

	def new
		@post = Post.new
	end 

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to blog_path, notice: "Your post has been created!"

		else 
			render :new
		end 
	end

	def show
		set_param
		
	end 


	def edit
		@post = Post.find(params[:id])
		redirect_to newpost_path

	end 

	def update
	end 

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to blog_path, alert: "your post was deleted"

	end 

	private

	def post_params
		params.require(:post).permit(:post, :title)
	end 

	def set_param
		@post = Post.find(params[:id])
	end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shyangden Phiroj</title>
  <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:100' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css">


<!-- Optional theme -->

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<!-- <link href="css/bootstrap.lightbox.css" rel="stylesheet" media="screen">
<script src="js/bootstrap.lightbox.js"></script> -->

</head>

<body>

          <div class="navlist">
            <span class="naming">Shyangden Phiroj</span>
            <ul class="ulist">
              <li class="appnav"><%= link_to "Contact", contacts_path %></li>
              <li class="appnav"><%= link_to "News & Announcements", blog_path %></li> 
              <li class="appnav"><%= link_to "Gallery", galleries_path %></li> 
              <li class="appnav"><%= link_to "Media", media_path %></li> 
              <li class="appnav"><%= link_to "Home", '/' %></li> 
            </ul>
          </div>
<!--   <div class="header" id="header-container">	
    <nav class="navbar navbar-default">
      <div class="conatiner">
        <div class="navbar-header"> -->

<!--           <a class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> 
    
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span> -->
            
<!--           </a>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right"> -->


<!--         </div>
      </div>
    </nav>
  </div> -->
				
	<%= yield %>

    <footer id="footernav">
    	<% if current_admin %>
    	 <%= link_to 'logout', destroy_admin_session_path, method: :delete %>
    	<% end %>
    </footer>


    <p class="notice"><%= notice %></p>
	  <p class="alert"><%= alert %></p>
    </body>
</html>

app/views/pages/blog.html.erb
<%= form_for (@gallery) do |f| %>
	<p>
		<%= f.label :event %>
		<%= f.text_field :event %>
	</p>
	
	<p>
		<%= f.submit "submit"%>
	</p>
<% end %>

app/views/pages/contact.html.erb
<script language="javascript">var sa_email_id = '56153-01c3d';var sa_sent_text = 'Thank you for contacting us. We will get back to you soon.';</script>
<script language="javascript" src="http://s1.smartaddon.com/sa_htmlform.js"></script>
<div id="contactform">
<form name=sa_htmlform style="margin:0px" onsubmit="return contactform()">
	<h1 class="contactheader"> Please Contact Us:</h1>
<table>
<tr>
	<td>Name:<br>
		<input type="text" name="name" />
	</td>
</tr>

<tr>
	<td>E-mail Address: 
		<br>
		<input type="text" name="email" required="true" />
	</td>
</tr>
<tr>
	<td>Subject: 
		<br>
		<input type="text" name="subject" required="true" />
	</td>
</tr>
<tr>
	<td>Message: 
		<br>
		<textarea name="message" cols="42" rows="9" required="true">
		</textarea>
	</td>
</tr>
<tr>
	<td>
		<input type="submit" value="Send Message" style="font-weight:bold">
	</td>
</tr>
</table>
</form>
</div>

app/views/pages/gallery.html.erb
 
 <% @galleries.each do |gallery| %>

 
  <p><%= gallery.event %></p>
 

 
 <% end %>
 <div class="images">
 <%= image_tag @picture.image.url(:medium) %>
</div>

app/views/pages/index.html.erb
<head>   
    <title>Shyangden Phiroj</title>

</head>

<body>


<div class='header'>
  <div style="position: fixed; width: 100%; height: 100%" >
    <iframe id="player" frameborder="0" height="100%" width="100%" 
      src="//www.youtube.com/embed/8yDzZ0KJjoU?modestbranding=1&autohide=0&showinfo=0&controls=1&enablejsapi=1&autoplay=1&vq=hd1080">
    </iframe>
  </div>

app/views/pages/media.html.erb
<div id="music">
    <h1 class='navname'>Shyangden Phiroj</h1>
        <div id='about'>
            <h1 class='about_title'>About</h1>
                <div id='connect'>
                    <p id='bio'>Based in Queens, New York, Shyangden Phiroj is a world-renown guitarist. A founding member of one of Nepal's most famous rock bands, 1974 AD, his playing style implements various genres, including Nepali folk, ragas, rock, funk, blues and jazz. </p>
                </div>
        </div>

        <h1 class='music_title'>Music</h1>
            <ul class="list-unstyled">
                <li><iframe width="500px" height="100px" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/214137704&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe></a></li>
                <br>
                <li><iframe width="500px" height="100px" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/198769237&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe></li>
                <br>
                <li><iframe width="500px" height="100px" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/200450413&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe></li>
            </ul>




        <div id='contact'>
            <h1 class='contact_title'>Contact</h1>
                <div id='connect'>
                    <p id='email'>For booking inquiries, please connect via the links below: </p>
                </div>
                    <div class='social'>

                      <span>  <a href="https://soundcloud.com/shyangden-phiroj" target="_blank"><img class='slinks' src="assets/sc2.png"></a>
                        <a href="https://www.facebook.com/pages/Phiroj-Shyangden/281762140542" target="_blank"><img class='slinks' src="assets/fb2.png"></a>
                        <a href="https://www.linkedin.com/pub/phiroj-shyangden/7a/948/186" target="_blank"><img class='slinks' src="assets/li2.png"></a>
                        <a href="https://www.youtube.com/channel/UCrHstpw9XwH9uydjNpl8d9g" target="_blank"><img class='slinks' src="assets/yt2.png"></a>
                        <a href="mailto:phirojmusic@gmail.com" target="_blank">
                        <img class="slinks" src="assets/mail.png"></a></span>
                    </div>
                </div>
        </div>